# Generated by Django 5.2 on 2025-05-26 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salud', models.IntegerField(default=0)),
                ('energia_espiritual', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('velocidad', models.IntegerField(default=0)),
                ('ataque', models.IntegerField(default=0)),
                ('nivel_necesario', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='resources/accesorios/')),
            ],
        ),
        migrations.CreateModel(
            name='Activa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coste_energia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coste_salud', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.99)])),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('efecto', models.JSONField(default=dict)),
                ('nivel_necesario', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ActivaEnemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('efecto', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('velocidad', models.IntegerField(default=0)),
                ('nivel_necesario', models.IntegerField(default=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='resources/armas/')),
            ],
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('salud_maxima', models.IntegerField(default=100)),
                ('salud', models.IntegerField(default=100)),
                ('ataque', models.IntegerField(default=10)),
                ('defensa', models.IntegerField(default=10)),
                ('velocidad', models.IntegerField(default=10)),
                ('dificultad', models.CharField(max_length=50)),
                ('experiencia_otorgada', models.IntegerField(default=0)),
                ('oro_otorgado', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('recompensa_especial', models.JSONField(blank=True, default=dict, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_enemigos/')),
                ('habilidad_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_1', to='battlebound_tactics.activaenemigo')),
                ('habilidad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_2', to='battlebound_tactics.activaenemigo')),
                ('habilidad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_3', to='battlebound_tactics.activaenemigo')),
            ],
        ),
        migrations.CreateModel(
            name='Pasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('efecto', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('enemigo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='battlebound_tactics.enemigo')),
                ('habilidades', models.JSONField(default=dict)),
                ('es_jefe_final', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Jefe',
                'verbose_name_plural': 'Jefes',
            },
            bases=('battlebound_tactics.enemigo',),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('clase', models.CharField(choices=[('Guerrero', 'Guerrero'), ('Mago', 'Mago'), ('Arquero', 'Arquero'), ('Luchador', 'Luchador'), ('Espiritualista', 'Espiritualista'), ('Astral', 'Astral')], default='Guerrero', max_length=50)),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('experiencia_maxima', models.IntegerField(default=1000)),
                ('alineacion', models.CharField(choices=[('Aliado', 'Aliado'), ('Neutro', 'Neutro'), ('Enemigo', 'Enemigo')], default='Neutro', max_length=10)),
                ('salud_maxima', models.IntegerField(default=1000)),
                ('salud', models.IntegerField(default=1000)),
                ('energia_espiritual_maxima', models.IntegerField(default=40)),
                ('energia_espiritual', models.IntegerField(default=40)),
                ('defensa', models.IntegerField(default=300)),
                ('velocidad', models.IntegerField(default=100)),
                ('ataque', models.IntegerField(default=300)),
                ('oro', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(blank=True, default=0, null=True)),
                ('derrotas', models.IntegerField(blank=True, default=0, null=True)),
                ('combate_abandonado', models.BooleanField(default=False)),
                ('combate_abandonado_id', models.IntegerField(blank=True, null=True)),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battlebound_tactics.accesorio')),
                ('arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battlebound_tactics.arma')),
                ('habilidad_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_1', to='battlebound_tactics.activa')),
                ('habilidad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_2', to='battlebound_tactics.activa')),
                ('habilidad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_3', to='battlebound_tactics.activa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habilidad_pasiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battlebound_tactics.pasiva')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('registro', models.TextField(blank=True, null=True)),
                ('turnos', models.IntegerField(default=0)),
                ('cooldowns_enemigo', models.JSONField(default=dict)),
                ('terminado', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, choices=[('victoria', 'Victoria'), ('derrota', 'Derrota')], max_length=10, null=True)),
                ('enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enemigo', to='battlebound_tactics.enemigo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jugador', to='battlebound_tactics.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(help_text='Formato: x1,y1,x2,y2', max_length=100)),
                ('tipo', models.CharField(choices=[('combate', 'Combate'), ('dialogo', 'Diálogo'), ('plantilla', 'Plantilla externa')], max_length=20)),
                ('plantilla_destino', models.CharField(blank=True, help_text="Nombre de plantilla para tipo 'plantilla'", max_length=100, null=True)),
                ('texto_dialogo', models.TextField(blank=True, help_text="Texto mostrado si el tipo es 'dialogo'", null=True)),
                ('enemigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battlebound_tactics.enemigo')),
            ],
        ),
    ]
