# Generated by Django 5.2 on 2025-05-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combate',
            name='enemigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enemigo', to='battlebound_tactics.enemigo'),
        ),
        migrations.AlterField(
            model_name='combate',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jugador', to='battlebound_tactics.jugador'),
        ),
    ]
