# Generated by Django 5.2 on 2025-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='clase',
            field=models.CharField(choices=[('Guerrero', 'Guerrero'), ('Mago', 'Mago'), ('Arquero', 'Arquero'), ('Luchador', 'Luchador'), ('Espiritualista', 'Espiritualista'), ('Astral', 'Astral')], default='Guerrero', max_length=50),
        ),
    ]
