# Generated by Django 5.2 on 2025-05-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='cooldowns_enemigo',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='HabilidadAsignadaEnemigo',
        ),
    ]
