# Generated by Django 5.2 on 2025-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='alineacion',
            field=models.CharField(choices=[('Aliado', 'Aliado'), ('Neutro', 'Neutro'), ('Enemigo', 'Enemigo')], default='Neutro', max_length=10),
        ),
    ]
