# Generated by Django 5.2 on 2025-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0002_jugador_alineacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='ataque',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='defensa',
            field=models.IntegerField(default=15),
        ),
    ]
