# Generated by Django 5.2 on 2025-05-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0002_alter_combate_enemigo_alter_combate_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoactivo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estadoactivo',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='combate',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='EstadoActivo',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
