# Generated by Django 5.2 on 2025-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0002_alter_jugador_clase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='chance_adicional',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='chance_critico',
        ),
        migrations.RemoveField(
            model_name='accesorio',
            name='chance_esquivar',
        ),
        migrations.RemoveField(
            model_name='pasiva',
            name='clase_objetivo',
        ),
        migrations.RemoveField(
            model_name='pasiva',
            name='desbloqueada',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='nivel_necesario',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arma',
            name='nivel_necesario',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='objeto',
            name='precio',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='pasiva',
            name='efecto',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='resources/accesorios/'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='resources/armas/'),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='energia_espiritual',
            field=models.IntegerField(default=models.IntegerField(default=50)),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='salud',
            field=models.IntegerField(default=models.IntegerField(default=100)),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='resources/objetos/'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='tipo',
            field=models.CharField(choices=[('consumible', 'Consumible'), ('material', 'Material'), ('historia', 'Historia'), ('coleccionable', 'Coleccionable'), ('botin', 'Botin')], max_length=20),
        ),
    ]
