# Generated by Django 5.2 on 2025-05-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0003_remove_estadoactivo_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('efecto', models.JSONField(default=dict)),
                ('nivel_necesario', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='enemigo',
            name='salud_maxima',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='ataque',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='defensa',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='salud',
            field=models.IntegerField(default=models.IntegerField(default=100)),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='velocidad',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='jugador',
            name='habilidad_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_1', to='battlebound_tactics.activa'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='habilidad_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_2', to='battlebound_tactics.activa'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='habilidad_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidad_3', to='battlebound_tactics.activa'),
        ),
    ]
