# Generated by Django 5.2 on 2025-05-07 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0004_activa_enemigo_salud_maxima_alter_enemigo_ataque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activa',
            name='coste_energia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='activa',
            name='coste_salud',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='activa',
            name='nivel_necesario',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
