# Generated by Django 5.2 on 2025-05-12 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0006_alter_jugador_energia_espiritual_alter_jugador_salud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivaEnemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('efecto', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='enemigo',
            name='nivel',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='activa',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='salud',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pasiva',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='enemigo',
            name='habilidad_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_1', to='battlebound_tactics.activaenemigo'),
        ),
        migrations.AddField(
            model_name='enemigo',
            name='habilidad_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_2', to='battlebound_tactics.activaenemigo'),
        ),
        migrations.AddField(
            model_name='enemigo',
            name='habilidad_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemigo_habilidad_3', to='battlebound_tactics.activaenemigo'),
        ),
        migrations.CreateModel(
            name='HabilidadAsignadaEnemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_actual', models.IntegerField(default=0)),
                ('enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_asignadas', to='battlebound_tactics.enemigo')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battlebound_tactics.activaenemigo')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(help_text='Formato: x1,y1,x2,y2', max_length=100)),
                ('tipo', models.CharField(choices=[('combate', 'Combate'), ('dialogo', 'Diálogo'), ('plantilla', 'Plantilla externa')], max_length=20)),
                ('plantilla_destino', models.CharField(blank=True, help_text="Nombre de plantilla para tipo 'plantilla'", max_length=100, null=True)),
                ('texto_dialogo', models.TextField(blank=True, help_text="Texto mostrado si el tipo es 'dialogo'", null=True)),
                ('enemigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='battlebound_tactics.enemigo')),
            ],
        ),
    ]
