# Generated by Django 5.2 on 2025-05-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0007_activaenemigo_enemigo_nivel_alter_activa_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='medidor_definitiva',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='piedras_dragon',
        ),
    ]
