# Generated by Django 5.2 on 2025-05-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0008_remove_jugador_medidor_definitiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enemigo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_enemigos/'),
        ),
    ]
