# Generated by Django 5.2 on 2025-05-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0009_combate_terminado_alter_enemigo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='derrotas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='victorias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
