# Generated by Django 5.2 on 2025-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0010_jugador_derrotas_jugador_victorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='combate_abandonado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jugador',
            name='combate_abandonado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
