# Generated by Django 5.2 on 2025-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebound_tactics', '0011_jugador_combate_abandonado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='resultado',
            field=models.CharField(blank=True, choices=[('victoria', 'Victoria'), ('derrota', 'Derrota')], max_length=10, null=True),
        ),
    ]
